# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SistemaFotovoltaico.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 847)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #383838;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E5E5E;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #1E1E1E;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #FFFFFF;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1121, 851))
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label_titulo = QtWidgets.QLabel(self.page_1)
        self.label_titulo.setGeometry(QtCore.QRect(0, 10, 1121, 61))
        self.label_titulo.setStyleSheet("QLabel {\n"
"    font-size: 40px;\n"
"    color: #FFA726;\n"
"}")
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.tableWidget = QtWidgets.QTableWidget(self.page_1)
        self.tableWidget.setGeometry(QtCore.QRect(60, 170, 1061, 421))
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    gridline-color: #505050;\n"
"    color: #E0E0E0;\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(5)
        self.tableWidget.setMidLineWidth(5)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget.setTabKeyNavigation(True)
        self.tableWidget.setProperty("showDropIndicator", True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(8)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(159)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(44)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(52)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(47)
        self.label_enunciado = QtWidgets.QLabel(self.page_1)
        self.label_enunciado.setGeometry(QtCore.QRect(60, 80, 461, 31))
        self.label_enunciado.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_enunciado.setObjectName("label_enunciado")
        self.label_rta1 = QtWidgets.QLabel(self.page_1)
        self.label_rta1.setGeometry(QtCore.QRect(100, 700, 291, 31))
        self.label_rta1.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_rta1.setObjectName("label_rta1")
        self.label_wattsTotales = QtWidgets.QLabel(self.page_1)
        self.label_wattsTotales.setGeometry(QtCore.QRect(400, 700, 151, 31))
        self.label_wattsTotales.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_wattsTotales.setText("")
        self.label_wattsTotales.setObjectName("label_wattsTotales")
        self.label_rta2 = QtWidgets.QLabel(self.page_1)
        self.label_rta2.setGeometry(QtCore.QRect(630, 700, 291, 31))
        self.label_rta2.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_rta2.setObjectName("label_rta2")
        self.label_consumoPromedio = QtWidgets.QLabel(self.page_1)
        self.label_consumoPromedio.setGeometry(QtCore.QRect(920, 700, 151, 31))
        self.label_consumoPromedio.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_consumoPromedio.setText("")
        self.label_consumoPromedio.setObjectName("label_consumoPromedio")
        self.label_titulo2 = QtWidgets.QLabel(self.page_1)
        self.label_titulo2.setGeometry(QtCore.QRect(130, 660, 241, 31))
        self.label_titulo2.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_titulo2.setObjectName("label_titulo2")
        self.label_titulo3 = QtWidgets.QLabel(self.page_1)
        self.label_titulo3.setGeometry(QtCore.QRect(650, 660, 241, 31))
        self.label_titulo3.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_titulo3.setObjectName("label_titulo3")
        self.pushButton_calcularDemanda = QtWidgets.QPushButton(self.page_1)
        self.pushButton_calcularDemanda.setGeometry(QtCore.QRect(400, 600, 241, 51))
        self.pushButton_calcularDemanda.setStyleSheet("QPushButton {\n"
"    background-color: #FFA726; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9800;\n"
"}")
        self.pushButton_calcularDemanda.setObjectName("pushButton_calcularDemanda")
        self.pushButton_calcularBaterias = QtWidgets.QPushButton(self.page_1)
        self.pushButton_calcularBaterias.setGeometry(QtCore.QRect(80, 770, 371, 51))
        self.pushButton_calcularBaterias.setStyleSheet("QPushButton {\n"
"    background-color: #e59866; \n"
"    border-radius: 10px;\n"
"    font-size: 20px;\n"
"    font-weight: bold; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #dc7633;\n"
"}")
        self.pushButton_calcularBaterias.setObjectName("pushButton_calcularBaterias")
        self.pushButton_calcularSistemaFotovoltaico = QtWidgets.QPushButton(self.page_1)
        self.pushButton_calcularSistemaFotovoltaico.setGeometry(QtCore.QRect(540, 770, 491, 51))
        self.pushButton_calcularSistemaFotovoltaico.setStyleSheet("QPushButton {\n"
"    background-color: #e59866; \n"
"    border-radius: 10px;\n"
"    font-size: 20px;\n"
"    font-weight: bold; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #dc7633;\n"
"}")
        self.pushButton_calcularSistemaFotovoltaico.setObjectName("pushButton_calcularSistemaFotovoltaico")
        self.spinBox_numeroCargas = QtWidgets.QSpinBox(self.page_1)
        self.spinBox_numeroCargas.setGeometry(QtCore.QRect(510, 81, 71, 31))
        self.spinBox_numeroCargas.setStyleSheet("QSpinBox {\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    border-bottom: 1px solid white;\n"
"}")
        self.spinBox_numeroCargas.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_numeroCargas.setMinimum(1)
        self.spinBox_numeroCargas.setObjectName("spinBox_numeroCargas")
        self.label_enunciado_2 = QtWidgets.QLabel(self.page_1)
        self.label_enunciado_2.setGeometry(QtCore.QRect(60, 130, 301, 31))
        self.label_enunciado_2.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_enunciado_2.setObjectName("label_enunciado_2")
        self.pushButton_generarTabla = QtWidgets.QPushButton(self.page_1)
        self.pushButton_generarTabla.setGeometry(QtCore.QRect(610, 80, 101, 41))
        self.pushButton_generarTabla.setStyleSheet("QPushButton {\n"
"    background-color: #FFA726; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9800;\n"
"}")
        self.pushButton_generarTabla.setObjectName("pushButton_generarTabla")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_tituloBancoBaterias = QtWidgets.QLabel(self.page_2)
        self.label_tituloBancoBaterias.setGeometry(QtCore.QRect(0, 30, 1121, 61))
        self.label_tituloBancoBaterias.setStyleSheet("QLabel {\n"
"    font-size: 40px;\n"
"    color: #FFA726;\n"
"}")
        self.label_tituloBancoBaterias.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tituloBancoBaterias.setObjectName("label_tituloBancoBaterias")
        self.label_eficiencia = QtWidgets.QLabel(self.page_2)
        self.label_eficiencia.setGeometry(QtCore.QRect(80, 140, 251, 31))
        self.label_eficiencia.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_eficiencia.setObjectName("label_eficiencia")
        self.lineEdit_eficienciaInversor = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_eficienciaInversor.setGeometry(QtCore.QRect(390, 140, 91, 31))
        self.lineEdit_eficienciaInversor.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_eficienciaInversor.setText("")
        self.lineEdit_eficienciaInversor.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_eficienciaInversor.setObjectName("lineEdit_eficienciaInversor")
        self.lineEdit_voltajeSistema = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_voltajeSistema.setGeometry(QtCore.QRect(390, 210, 91, 31))
        self.lineEdit_voltajeSistema.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_voltajeSistema.setText("")
        self.lineEdit_voltajeSistema.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_voltajeSistema.setObjectName("lineEdit_voltajeSistema")
        self.label_voltajeSistema = QtWidgets.QLabel(self.page_2)
        self.label_voltajeSistema.setGeometry(QtCore.QRect(80, 210, 301, 31))
        self.label_voltajeSistema.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_voltajeSistema.setObjectName("label_voltajeSistema")
        self.label_autonomia = QtWidgets.QLabel(self.page_2)
        self.label_autonomia.setGeometry(QtCore.QRect(80, 280, 251, 31))
        self.label_autonomia.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_autonomia.setObjectName("label_autonomia")
        self.lineEdit_autonomia = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_autonomia.setGeometry(QtCore.QRect(390, 280, 91, 31))
        self.lineEdit_autonomia.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_autonomia.setText("")
        self.lineEdit_autonomia.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_autonomia.setObjectName("lineEdit_autonomia")
        self.lineEdit_capacidadBateria = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_capacidadBateria.setGeometry(QtCore.QRect(390, 350, 91, 31))
        self.lineEdit_capacidadBateria.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_capacidadBateria.setText("")
        self.lineEdit_capacidadBateria.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_capacidadBateria.setObjectName("lineEdit_capacidadBateria")
        self.label_capacidadBateria = QtWidgets.QLabel(self.page_2)
        self.label_capacidadBateria.setGeometry(QtCore.QRect(80, 350, 301, 31))
        self.label_capacidadBateria.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_capacidadBateria.setObjectName("label_capacidadBateria")
        self.lineEdit_factorDescarga = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_factorDescarga.setGeometry(QtCore.QRect(390, 420, 91, 31))
        self.lineEdit_factorDescarga.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_factorDescarga.setText("")
        self.lineEdit_factorDescarga.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_factorDescarga.setObjectName("lineEdit_factorDescarga")
        self.label_factorDescarga = QtWidgets.QLabel(self.page_2)
        self.label_factorDescarga.setGeometry(QtCore.QRect(80, 420, 251, 31))
        self.label_factorDescarga.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_factorDescarga.setObjectName("label_factorDescarga")
        self.lineEdit_voltajeBateria = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_voltajeBateria.setGeometry(QtCore.QRect(390, 490, 91, 31))
        self.lineEdit_voltajeBateria.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_voltajeBateria.setText("")
        self.lineEdit_voltajeBateria.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_voltajeBateria.setObjectName("lineEdit_voltajeBateria")
        self.label_voltajeBateria = QtWidgets.QLabel(self.page_2)
        self.label_voltajeBateria.setGeometry(QtCore.QRect(80, 490, 251, 31))
        self.label_voltajeBateria.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_voltajeBateria.setObjectName("label_voltajeBateria")
        self.label_capacidadTotalAh = QtWidgets.QLabel(self.page_2)
        self.label_capacidadTotalAh.setGeometry(QtCore.QRect(300, 600, 151, 31))
        self.label_capacidadTotalAh.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_capacidadTotalAh.setText("")
        self.label_capacidadTotalAh.setObjectName("label_capacidadTotalAh")
        self.label_tituloAh = QtWidgets.QLabel(self.page_2)
        self.label_tituloAh.setGeometry(QtCore.QRect(80, 600, 201, 31))
        self.label_tituloAh.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_tituloAh.setObjectName("label_tituloAh")
        self.label_tituloWh = QtWidgets.QLabel(self.page_2)
        self.label_tituloWh.setGeometry(QtCore.QRect(80, 650, 211, 31))
        self.label_tituloWh.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_tituloWh.setObjectName("label_tituloWh")
        self.label_tituloParalelo = QtWidgets.QLabel(self.page_2)
        self.label_tituloParalelo.setGeometry(QtCore.QRect(550, 600, 331, 31))
        self.label_tituloParalelo.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_tituloParalelo.setObjectName("label_tituloParalelo")
        self.label_capacidadTotalWh = QtWidgets.QLabel(self.page_2)
        self.label_capacidadTotalWh.setGeometry(QtCore.QRect(300, 650, 151, 31))
        self.label_capacidadTotalWh.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_capacidadTotalWh.setText("")
        self.label_capacidadTotalWh.setObjectName("label_capacidadTotalWh")
        self.label_tituloSerie = QtWidgets.QLabel(self.page_2)
        self.label_tituloSerie.setGeometry(QtCore.QRect(550, 650, 331, 31))
        self.label_tituloSerie.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_tituloSerie.setObjectName("label_tituloSerie")
        self.label_bateriasParalelo = QtWidgets.QLabel(self.page_2)
        self.label_bateriasParalelo.setGeometry(QtCore.QRect(890, 600, 151, 31))
        self.label_bateriasParalelo.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_bateriasParalelo.setText("")
        self.label_bateriasParalelo.setObjectName("label_bateriasParalelo")
        self.label_bateriasSerie = QtWidgets.QLabel(self.page_2)
        self.label_bateriasSerie.setGeometry(QtCore.QRect(860, 650, 151, 31))
        self.label_bateriasSerie.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_bateriasSerie.setText("")
        self.label_bateriasSerie.setObjectName("label_bateriasSerie")
        self.label_bateriasTotales = QtWidgets.QLabel(self.page_2)
        self.label_bateriasTotales.setGeometry(QtCore.QRect(350, 710, 151, 31))
        self.label_bateriasTotales.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_bateriasTotales.setText("")
        self.label_bateriasTotales.setObjectName("label_bateriasTotales")
        self.label_tituloTotal = QtWidgets.QLabel(self.page_2)
        self.label_tituloTotal.setGeometry(QtCore.QRect(80, 710, 261, 31))
        self.label_tituloTotal.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #fac01b;\n"
"    font-weight: bold;\n"
"}")
        self.label_tituloTotal.setObjectName("label_tituloTotal")
        self.pushButton_calcularBancoBaterias = QtWidgets.QPushButton(self.page_2)
        self.pushButton_calcularBancoBaterias.setGeometry(QtCore.QRect(730, 320, 161, 51))
        self.pushButton_calcularBancoBaterias.setStyleSheet("QPushButton {\n"
"    background-color: #FFA726; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9800;\n"
"}")
        self.pushButton_calcularBancoBaterias.setObjectName("pushButton_calcularBancoBaterias")
        self.pushButton_volver = QtWidgets.QPushButton(self.page_2)
        self.pushButton_volver.setGeometry(QtCore.QRect(930, 770, 161, 51))
        self.pushButton_volver.setStyleSheet("QPushButton {\n"
"    background-color: #c7bb29; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ece272;\n"
"    color: #626260;\n"
"}")
        self.pushButton_volver.setObjectName("pushButton_volver")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_tituloSistemaFotovoltaico = QtWidgets.QLabel(self.page_3)
        self.label_tituloSistemaFotovoltaico.setGeometry(QtCore.QRect(0, 30, 1121, 61))
        self.label_tituloSistemaFotovoltaico.setStyleSheet("QLabel {\n"
"    font-size: 40px;\n"
"    color: #FFA726;\n"
"}")
        self.label_tituloSistemaFotovoltaico.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tituloSistemaFotovoltaico.setObjectName("label_tituloSistemaFotovoltaico")
        self.lineEdit_eficienciaInversor_2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_eficienciaInversor_2.setGeometry(QtCore.QRect(380, 120, 91, 31))
        self.lineEdit_eficienciaInversor_2.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_eficienciaInversor_2.setText("")
        self.lineEdit_eficienciaInversor_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_eficienciaInversor_2.setObjectName("lineEdit_eficienciaInversor_2")
        self.lineEdit_eficienciaBateria = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_eficienciaBateria.setGeometry(QtCore.QRect(380, 190, 91, 31))
        self.lineEdit_eficienciaBateria.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_eficienciaBateria.setText("")
        self.lineEdit_eficienciaBateria.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_eficienciaBateria.setObjectName("lineEdit_eficienciaBateria")
        self.lineEdit_horasSolarPico = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_horasSolarPico.setGeometry(QtCore.QRect(380, 260, 91, 31))
        self.lineEdit_horasSolarPico.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_horasSolarPico.setText("")
        self.lineEdit_horasSolarPico.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_horasSolarPico.setObjectName("lineEdit_horasSolarPico")
        self.lineEdit_corrientePicoModulo = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_corrientePicoModulo.setGeometry(QtCore.QRect(380, 330, 91, 31))
        self.lineEdit_corrientePicoModulo.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_corrientePicoModulo.setText("")
        self.lineEdit_corrientePicoModulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_corrientePicoModulo.setObjectName("lineEdit_corrientePicoModulo")
        self.lineEdit_voltajeSistema_2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_voltajeSistema_2.setGeometry(QtCore.QRect(380, 400, 91, 31))
        self.lineEdit_voltajeSistema_2.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_voltajeSistema_2.setText("")
        self.lineEdit_voltajeSistema_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_voltajeSistema_2.setObjectName("lineEdit_voltajeSistema_2")
        self.lineEdit_voltajeModulo = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_voltajeModulo.setGeometry(QtCore.QRect(380, 470, 91, 31))
        self.lineEdit_voltajeModulo.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_voltajeModulo.setText("")
        self.lineEdit_voltajeModulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_voltajeModulo.setObjectName("lineEdit_voltajeModulo")
        self.lineEdit_cortocircuitoModulo = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_cortocircuitoModulo.setGeometry(QtCore.QRect(380, 540, 91, 31))
        self.lineEdit_cortocircuitoModulo.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-bottom: 2px solid white;\n"
"    background-color: transparent;\n"
"    font-size: 23px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #4d4d4d;\n"
"}")
        self.lineEdit_cortocircuitoModulo.setText("")
        self.lineEdit_cortocircuitoModulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_cortocircuitoModulo.setObjectName("lineEdit_cortocircuitoModulo")
        self.label_totalPaneles = QtWidgets.QLabel(self.page_3)
        self.label_totalPaneles.setGeometry(QtCore.QRect(330, 730, 151, 31))
        self.label_totalPaneles.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_totalPaneles.setText("")
        self.label_totalPaneles.setObjectName("label_totalPaneles")
        self.label_potenciaInversor = QtWidgets.QLabel(self.page_3)
        self.label_potenciaInversor.setGeometry(QtCore.QRect(850, 670, 151, 31))
        self.label_potenciaInversor.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_potenciaInversor.setText("")
        self.label_potenciaInversor.setObjectName("label_potenciaInversor")
        self.label_cortocircuitoModulo = QtWidgets.QLabel(self.page_3)
        self.label_cortocircuitoModulo.setGeometry(QtCore.QRect(70, 540, 271, 31))
        self.label_cortocircuitoModulo.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_cortocircuitoModulo.setObjectName("label_cortocircuitoModulo")
        self.label_panelesParalelo = QtWidgets.QLabel(self.page_3)
        self.label_panelesParalelo.setGeometry(QtCore.QRect(390, 670, 151, 31))
        self.label_panelesParalelo.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_panelesParalelo.setText("")
        self.label_panelesParalelo.setObjectName("label_panelesParalelo")
        self.label_eficienciaBateria = QtWidgets.QLabel(self.page_3)
        self.label_eficienciaBateria.setGeometry(QtCore.QRect(70, 190, 251, 31))
        self.label_eficienciaBateria.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_eficienciaBateria.setObjectName("label_eficienciaBateria")
        self.label_panelesSerie = QtWidgets.QLabel(self.page_3)
        self.label_panelesSerie.setGeometry(QtCore.QRect(360, 620, 151, 31))
        self.label_panelesSerie.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_panelesSerie.setText("")
        self.label_panelesSerie.setObjectName("label_panelesSerie")
        self.label_tituloTotalPaneles = QtWidgets.QLabel(self.page_3)
        self.label_tituloTotalPaneles.setGeometry(QtCore.QRect(60, 730, 261, 31))
        self.label_tituloTotalPaneles.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #fac01b;\n"
"    font-weight: bold;\n"
"}")
        self.label_tituloTotalPaneles.setObjectName("label_tituloTotalPaneles")
        self.label_tituloPotenciaInversor = QtWidgets.QLabel(self.page_3)
        self.label_tituloPotenciaInversor.setGeometry(QtCore.QRect(560, 670, 281, 31))
        self.label_tituloPotenciaInversor.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_tituloPotenciaInversor.setObjectName("label_tituloPotenciaInversor")
        self.label_corrientePicoModulo = QtWidgets.QLabel(self.page_3)
        self.label_corrientePicoModulo.setGeometry(QtCore.QRect(70, 330, 281, 31))
        self.label_corrientePicoModulo.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_corrientePicoModulo.setObjectName("label_corrientePicoModulo")
        self.label_voltajeSistema_2 = QtWidgets.QLabel(self.page_3)
        self.label_voltajeSistema_2.setGeometry(QtCore.QRect(70, 400, 301, 31))
        self.label_voltajeSistema_2.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_voltajeSistema_2.setObjectName("label_voltajeSistema_2")
        self.label_eficiencia_2 = QtWidgets.QLabel(self.page_3)
        self.label_eficiencia_2.setGeometry(QtCore.QRect(70, 120, 251, 31))
        self.label_eficiencia_2.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_eficiencia_2.setObjectName("label_eficiencia_2")
        self.label_tituloPanelesParalelo = QtWidgets.QLabel(self.page_3)
        self.label_tituloPanelesParalelo.setGeometry(QtCore.QRect(60, 670, 321, 31))
        self.label_tituloPanelesParalelo.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_tituloPanelesParalelo.setObjectName("label_tituloPanelesParalelo")
        self.label_tituloPanelesSerie = QtWidgets.QLabel(self.page_3)
        self.label_tituloPanelesSerie.setGeometry(QtCore.QRect(60, 620, 291, 31))
        self.label_tituloPanelesSerie.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_tituloPanelesSerie.setObjectName("label_tituloPanelesSerie")
        self.label_voltajeModulo = QtWidgets.QLabel(self.page_3)
        self.label_voltajeModulo.setGeometry(QtCore.QRect(70, 470, 291, 31))
        self.label_voltajeModulo.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_voltajeModulo.setObjectName("label_voltajeModulo")
        self.label_horasSolarPico = QtWidgets.QLabel(self.page_3)
        self.label_horasSolarPico.setGeometry(QtCore.QRect(70, 260, 241, 31))
        self.label_horasSolarPico.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_horasSolarPico.setObjectName("label_horasSolarPico")
        self.label_tituloVoltajeInversor = QtWidgets.QLabel(self.page_3)
        self.label_tituloVoltajeInversor.setGeometry(QtCore.QRect(560, 720, 281, 31))
        self.label_tituloVoltajeInversor.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_tituloVoltajeInversor.setObjectName("label_tituloVoltajeInversor")
        self.label_tituloCapacidadControlador = QtWidgets.QLabel(self.page_3)
        self.label_tituloCapacidadControlador.setGeometry(QtCore.QRect(560, 620, 281, 31))
        self.label_tituloCapacidadControlador.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"    color: #FFD54F;\n"
"    font-weight: bold;\n"
"}")
        self.label_tituloCapacidadControlador.setObjectName("label_tituloCapacidadControlador")
        self.label_voltajeInversor = QtWidgets.QLabel(self.page_3)
        self.label_voltajeInversor.setGeometry(QtCore.QRect(850, 720, 151, 31))
        self.label_voltajeInversor.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_voltajeInversor.setText("")
        self.label_voltajeInversor.setObjectName("label_voltajeInversor")
        self.label_capacidadControlador = QtWidgets.QLabel(self.page_3)
        self.label_capacidadControlador.setGeometry(QtCore.QRect(850, 620, 151, 31))
        self.label_capacidadControlador.setStyleSheet("QLabel {\n"
"    font-size: 20px;\n"
"}")
        self.label_capacidadControlador.setText("")
        self.label_capacidadControlador.setObjectName("label_capacidadControlador")
        self.pushButton_calcularSistemaPaneles = QtWidgets.QPushButton(self.page_3)
        self.pushButton_calcularSistemaPaneles.setGeometry(QtCore.QRect(730, 320, 161, 51))
        self.pushButton_calcularSistemaPaneles.setStyleSheet("QPushButton {\n"
"    background-color: #FFA726; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FF9800;\n"
"}")
        self.pushButton_calcularSistemaPaneles.setObjectName("pushButton_calcularSistemaPaneles")
        self.pushButton_volver_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_volver_2.setGeometry(QtCore.QRect(930, 770, 161, 51))
        self.pushButton_volver_2.setStyleSheet("QPushButton {\n"
"    background-color: #c7bb29; \n"
"    border-radius: 10px;\n"
"    font-size: 20px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #ece272;\n"
"    color: #626260;\n"
"}")
        self.pushButton_volver_2.setObjectName("pushButton_volver_2")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "CÁLCULO DE DEMANDA"))
        self.tableWidget.setSortingEnabled(False)
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "CARGAS INDIVIDUALES"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "CANTIDAD"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "WATTS"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "HORAS DE USO/DÍA"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "DÍAS DE USO/SEMANA"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "WATTS CONSUMIDOS"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_enunciado.setText(_translate("MainWindow", "Ingrese el número de cargas que desea calcular:"))
        self.label_rta1.setText(_translate("MainWindow", "WATTS TOTALES CONECTADOS:"))
        self.label_rta2.setText(_translate("MainWindow", "CONSUMO PROMEDIO DIARIO:"))
        self.label_titulo2.setText(_translate("MainWindow", "Demanda de potencia"))
        self.label_titulo3.setText(_translate("MainWindow", "Demanda de energía"))
        self.pushButton_calcularDemanda.setText(_translate("MainWindow", "CALCULAR DEMANDA"))
        self.pushButton_calcularBaterias.setText(_translate("MainWindow", "CALCULAR BANCO DE BATERÍAS"))
        self.pushButton_calcularSistemaFotovoltaico.setText(_translate("MainWindow", "CALCULAR SISTEMA FOTOVOLTAICO"))
        self.label_enunciado_2.setText(_translate("MainWindow", "Ingrese los datos de cada carga:"))
        self.pushButton_generarTabla.setText(_translate("MainWindow", "Enviar"))
        self.label_tituloBancoBaterias.setText(_translate("MainWindow", "BANCO DE BATERÍAS"))
        self.label_eficiencia.setText(_translate("MainWindow", "Eficiencia del inversor (%):"))
        self.label_voltajeSistema.setText(_translate("MainWindow", "Voltaje del sistema en C.D. (V):"))
        self.label_autonomia.setText(_translate("MainWindow", "Autonomía (días):"))
        self.label_capacidadBateria.setText(_translate("MainWindow", "Capacidad de cada batería (Ah):"))
        self.label_factorDescarga.setText(_translate("MainWindow", "Factor de descarga (%):"))
        self.label_voltajeBateria.setText(_translate("MainWindow", "Voltaje de cada batería (V):"))
        self.label_tituloAh.setText(_translate("MainWindow", "Capacidad total Ah:"))
        self.label_tituloWh.setText(_translate("MainWindow", "Capacidad total Wh:"))
        self.label_tituloParalelo.setText(_translate("MainWindow", "Número de baterías en paralelo:"))
        self.label_tituloSerie.setText(_translate("MainWindow", "Número de baterías en serie:"))
        self.label_tituloTotal.setText(_translate("MainWindow", "Número total de baterías:"))
        self.pushButton_calcularBancoBaterias.setText(_translate("MainWindow", "CALCULAR"))
        self.pushButton_volver.setText(_translate("MainWindow", "VOLVER"))
        self.label_tituloSistemaFotovoltaico.setText(_translate("MainWindow", "SISTEMA FOTOVOLTAICO"))
        self.label_cortocircuitoModulo.setText(_translate("MainWindow", "Cortocircuito del módulo (A):"))
        self.label_eficienciaBateria.setText(_translate("MainWindow", "Eficiencia de la batería (%):"))
        self.label_tituloTotalPaneles.setText(_translate("MainWindow", "Número total de paneles:"))
        self.label_tituloPotenciaInversor.setText(_translate("MainWindow", "Potencia total del inversor:"))
        self.label_corrientePicoModulo.setText(_translate("MainWindow", "Corriente pico por módulo (A):"))
        self.label_voltajeSistema_2.setText(_translate("MainWindow", "Voltaje del sistema en C.D (V):"))
        self.label_eficiencia_2.setText(_translate("MainWindow", "Eficiencia del inversor (%):"))
        self.label_tituloPanelesParalelo.setText(_translate("MainWindow", "Número de paneles en paralelo:"))
        self.label_tituloPanelesSerie.setText(_translate("MainWindow", "Número de paneles en serie:"))
        self.label_voltajeModulo.setText(_translate("MainWindow", "Voltaje nominal del módulo (V):"))
        self.label_horasSolarPico.setText(_translate("MainWindow", "Horas solar pico (horas):"))
        self.label_tituloVoltajeInversor.setText(_translate("MainWindow", "Voltaje en C.D. del inversor:"))
        self.label_tituloCapacidadControlador.setText(_translate("MainWindow", "Capacidad del controlador:"))
        self.pushButton_calcularSistemaPaneles.setText(_translate("MainWindow", "CALCULAR"))
        self.pushButton_volver_2.setText(_translate("MainWindow", "VOLVER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
